from pydantic import BaseModel, field_validator, ConfigDict
from typing import Optional
from decimal import Decimal
from datetime import datetime
import uuid

from app.schemas.common import RefundStatus


class RefundCreateRequest(BaseModel):
    """
    POST /refunds — agent requests a refund for a transaction.
    The client generates idempotency_key to prevent duplicates on retry.
    """
    ticket_id: uuid.UUID
    transaction_id: uuid.UUID
    amount: Decimal
    idempotency_key: str  # UUID string generated by the frontend

    @field_validator("amount")
    @classmethod
    def amount_must_be_positive(cls, v: Decimal) -> Decimal:
        if v <= 0:
            raise ValueError("Refund amount must be greater than zero")
        return v

    @field_validator("idempotency_key")
    @classmethod
    def idempotency_key_not_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Idempotency key cannot be empty")
        return v.strip()


class RefundApproveRequest(BaseModel):
    """
    PATCH /refunds/{id}/approve — supervisor approves or rejects.
    rejection_reason is required when approved=False.
    """
    approved: bool
    rejection_reason: Optional[str] = None

    @field_validator("rejection_reason")
    @classmethod
    def reason_required_on_rejection(cls, v: Optional[str], info) -> Optional[str]:
        # We check in the service layer since 'approved' is needed here
        # The service will enforce: if not approved → reason required
        if v:
            return v.strip()
        return v


class RefundResponse(BaseModel):
    """Full refund detail."""
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    ticket_id: uuid.UUID
    transaction_id: uuid.UUID
    idempotency_key: str
    amount: Decimal
    status: str
    rejection_reason: Optional[str]
    requested_at: datetime
    approved_at: Optional[datetime]
    processed_at: Optional[datetime]
    created_at: datetime


class RefundListItem(BaseModel):
    """Minimal refund view for list endpoints."""
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    ticket_id: uuid.UUID
    amount: Decimal
    status: str
    requested_at: datetime